### ISSUE TITLE
@hpcc-js/wasm-graphviz 1.8.0 load failed

### ISSUE THREAD

**Issue by prgrmrwy** [hpcc-systems/hpcc-js-wasm#305]
i directly use @hpcc-js/wasm-graphviz in js, in 1.8.0, if i call the `Graphviz.load()`, there will be an error called: `Uncaught (in promise) Error: Cannot find module 'graphvizlib.wasm'`, I'm not sure if it only in 1.8.0, but it works in 1.7.0 in my code

<img width="982" alt="Image" src="https://github.com/user-attachments/assets/a7f8fae2-e00a-44f6-9fe5-a9c096ab5932" />

**Comment by GordonSmith** [comment]
I suspect your bundler is picking up `@hpcc-js/wasm-graphviz/src/index.ts` and not `@hpcc-js/wasm-graphviz/dist/index.js`?

**Comment by farzadali3** [comment]
I also started getting the same error last week out of nowhere. I am using `"@hpcc-js/wasm-graphviz": "^1.2.0",` and I tried updating it to the latest `1.8` but still didn't work.

<img width="524" alt="Image" src="https://github.com/user-attachments/assets/151ddaa7-4aab-4270-8c3b-ed80d3ccea88" />

**Comment by GordonSmith** [comment]
I believe this is resolved now.  The second UMD won't load due to CORS, which is expected given the setup.

**Comment by farzadali3** [comment]
Just installed the latest `1.9` and still getting the same err

<img width="453" height="63" alt="Image" src="https://github.com/user-attachments/assets/12a617af-46bd-4357-a20c-f4bca9050d1b" />

**Comment by GordonSmith** [comment]
Can you share h

**Comment by GordonSmith** [comment]
Actually the final fix isn't in 1.9.0, can you retest with 1.9.1?

**Comment by GordonSmith** [comment]
FWIW - This regression is caused by a change in emcc js code generation, which in turn also has a two potential issues - I will be sending the fix to them in due course.

**Comment by farzadali3** [comment]
Nope, didn't work

<img width="992" height="52" alt="Image" src="https://github.com/user-attachments/assets/2967b4c2-4cdb-453c-ab6a-da9c5f5f0d1d" />
<img width="441" height="82" alt="Image" src="https://github.com/user-attachments/assets/876e6fd6-415d-4949-a04a-2b9467af7dbe" />
